web:
  build: . 
  ports:
    - "8080:80"
  volumes:
    - ./src:/var/www
    - ./src/vhost.conf:/etc/nginx/sites-enabled/default
  links:
    - php
php:
  image: nmcteam/php56
  expose:
    - "9000"
  volumes:
    - ./src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./src:/var/www
  links:
    - db
db:
  image: sameersbn/mysql
  volumes:
    - /var/lib/mysql
  ports: 
    - "3306:3306"
  environment:
    - DB_NAME=demoDb
    - DB_USER=demoUser
    - DB_PASS=demoPass
